### ISSUE TITLE
Why would anyone ever do this

### ISSUE THREAD

**Issue by menof36go** [Henotu/TTT2-Statistics#2]
https://github.com/Henotu/TTT2-Statistics/blob/02b5bea3b1289228d62dae6dd1db16023ff57f3b/lua/autorun/client/cl_stat_record.lua#L8

**Comment by menof36go** [comment]
Atleast call it StatBugfix099 or sth smh

**Comment by Henotu** [comment]
Fixed all function and variables names; I will not change the old Database names for now
